[package]
name = "get_call"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1.45.1", features = ["sync", "rt-multi-thread", "macros"] }
serde_json = "1.0.140"
