[package]
name = "grpc_crud"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
tokio = {version = "1.46.1", features = ["macros", "rt-multi-thread"]}
tonic = "0.13.1"

[build-dependencies]
tonic-build = "*"
